config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: %i[index show new create] do
    resources :reviews, only: %i[create]
  end
  root 'restaurants#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = %w[chinese italian japanese french belgian]

  validates :name, :address, :category, presence: true
  validates :category, acceptance: { accept: CATEGORY }

  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true

  validates :rating, numericality: { only_integer: true }
  validates :rating, acceptance: { accept: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant

    if @review.save
      redirect_to @restaurant
    else
      render 'restaurants/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand p-3" href="/restaurants">Yelp MVP</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
  </div>
</nav>
      <div class="container py-5">
        <%= yield %>
      </div>

    </body>

</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name, error: 'Name is mandatory, please specify one' %>
  <%= f.input :address, error: 'Address is mandatory' %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORY, error: 'Category is mandatory' %>
  <%= f.button :submit, class: 'btn btn-success'%>
<% end %>

app/views/restaurants/_restaurant.html.erb
<h1>
  <%= @restaurant.name %>
</h1>

<p>
  <%= @restaurant.address %>
</p>

<p>
  <%= @restaurant.phone_number %>
</p>

<p>
  <%= @restaurant.category %>
</p>

app/views/restaurants/_review_form.html.erb
<h4>
  Add Review
</h4>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, placeholder: 'Input rating 1-5' %>
  <%= f.input :content %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/restaurants/_reviews.html.erb
<div class="my-4">
  <h2>Reviews</h2>
  <ul>
    <% @restaurant.reviews.each do |review| %>
      <li>
        <%= review.rating %> |
        <%= review.content %>
      </li>
    <% end %>
  </ul>
</div>

app/views/restaurants/index.html.erb
<ul class="my-5 text-center" style="align-items:center;">
  <% @restaurants.each do |restaurant| %>
    <li class="card my-5 p-5 rounded shadow" style="width: 30%;">

      <h2>
        <%= restaurant.name %>
      </h2>

      <%= restaurant.category %>

      <%= link_to "See details", restaurant_path(restaurant), class: "btn btn-primary my-3", style: "align-items:center;width:100px;align-self:center"%>

    </li>
  <% end %>
</ul>
<%= link_to "Add a restaurant", new_restaurant_path, class: "btn btn-warning"%>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>


<%= link_to 'Back to restaurants', restaurants_path %>

app/views/restaurants/show.html.erb
<%= render 'restaurant',restaurant: @restaurant %>

<%= render 'reviews', review: @review %>

<%= render 'review_form', restaurant: @restaurant, review: @review %>

<%= link_to 'Back to restaurants', restaurants_path %>